name: Mirror to Bitbucket

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true # optional
          fetch-depth: 6
      - name: Unshallow repo
        run: git fetch --unshallow origin
      - name: mirror-repository
        uses: yesolutions/mirror-action@v0.6.0
        with:
          # The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes.
          REMOTE_NAME: bmirror # optional
          # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
          REMOTE: https://bitbucket.org/Grass_block/luminous.git # optional
          # Username for remote repository
          GIT_USERNAME: Grass_block # optional
          # The git https password or token for the remote repository
          GIT_PASSWORD: ${{ secrets.BITBUCKRT_PASS }} # optional
          DEBUG: true